services:
    posrgresql:
        image: postgres:16-alpine
        container_name: postgresql
        restart: always
        environment:
            # uses environment variable defined in .env
            POSTGRES_USER: ${POSTGRESQL_USER}
            POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
            POSTGRES_DB: ${POSTGRESQL_DB}

        # map storage volume on local machine to container
        # directory (ensures data persists even if container is removed)
        volumes:
            - postgresql-data:/var/lib/postgresql/data

        # map local machine port to container port
        ports:
            - "5432:5432"

# define named volumes available to services
volumes:
    postgresql-data:
